// This is the main file for GVZork written in C++.
#include <iostream>
#include "item.h"
#include "npc.h"
#include "location.h"
#include "game.h"

int main() {
    // // Testing Item - works
    // Item* myItem = new Item("Bottle", "Just a bottle", 250, 100.5);
    // std::cout << *myItem << std::endl;
    

    // // Testing Npc - works
    // Npc* myNpc = new Npc("Clay", "Just a guy");
    // std::cout << *myNpc << std::endl;
    

    // myNpc->addMessage("Hello There");
    // myNpc->addMessage("Seeya later");

    // std::cout << myNpc->getMessage() << std::endl;
    // std::cout << myNpc->getMessage() << std::endl;
    // std::cout << myNpc->getMessage() << std::endl;

    // // Testing Location
    // Location* myLocation = new Location("Macinac", "CS Building");
    // Location* mySecondLocation = new Location("Manitou", "Random Building");
    
    // myLocation->addNpc(*myNpc);
    // myLocation->addItem(*myItem);
    // // Generated by ChatGPT -- should work I think
    // myLocation->addLocation("north", std::ref(*mySecondLocation));

    // std::cout << *myLocation << std::endl;

    // delete myItem;
    // delete myNpc;
    // delete myLocation;
    // delete mySecondLocation;

    // return 0;

    Game* myGame = new Game();

    myGame->play();

    return 0;
}